[package]
name = "mmc-rs"
version = "2.0.0"
edition = "2021"
description = "Minimalist DDC/CI monitor control CLI"
repository = "https://github.com/Hexalyse/mmc-rs"

[dependencies]
ddc-hi = "0.4.1"
mccs-caps = "0.1.3"
clap = { version = "4.6.6", features = ["derive"] }
anyhow = "1.0.104"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
# opt-level = "z" # Optimize for space instead of speed
